### ISSUE TITLE
Implement voucherFunctionData param in registry and user contracts

### ISSUE THREAD

**Issue by jamslevy** [taptrust/voucher-protocol#6]
A new parameter for `VouchersRegistry.addContractVouchers` and `VoucherUser.requestContractVouchers` will be added, with the name `voucherFunctionData`.  The addition of this parameter makes it possible for the voucher donor and/or redeeming user to decide which function and arguments to use in the recipient contract that will receive voucher funds. 

This `voucherFunctionData` parameter is an array for `addContractVouchers` allowing for multiple values, and a single value for `VoucherUser.requestContractVouchers`. It is currently required for `VoucherUser.requestContractVouchers` and optional for `VouchersRegistry.addContractVouchers`  by specifying an empty value. 

The value format is a string and can be generated using methods such as `web3.eth.abi.encodefunctioncall` or `web3.encodeABI` by the client when provided by the function and the arguments to use. 

An example value in this format:

```
0xa9059cbb0000000000000000000000007adee867ea91533879d083dd47ea81f0eee3a37e000000000000000000000000000000000000000000000000d02ab486cedbffff
```

There are a couple of scenarios for how this works in practice:

- The donor specifies one or more `voucherFunctionData` values when adding voucher funds. This should setup the voucher so that only one of these values can be specified by the redeeming user, and all other values will result in an error.  The user needs to specify the supported `voucherFunctionData` value they want to use. 

- The donor does not specify  `voucherFunctionData` values, and the user needs to specify the the `voucherFunctionData` value they want to use, although it can be any data value that would result in a successful transaction with the recipient contract. 

At the time of voucher redemption, it is first verified that  `voucherFunctionData`  is supported, and then uses it to create the transaction to the recipient contract. 

The way this would be implemented in Solidity is:

```
require(contractAddress.call(voucherFunctionData, msg.value));

```

- Because string arrays are not supported, the first implementation of this does not use an array for `VouchersRegistry.addContractVouchers` . If `0x` only appears at the beginning of data values (?) then it may be possible to pass in multiple values as a single concatenated value and parse it from within the contract. The first implementation is also very simple in that if `voucherFunctionData` has been defined by the donor, any value provided by the redeeming user is not used. 

- It would be possible if the donor only provided a single value for `voucherFunctionData` to not make the `voucherFunctionData` argument required by the user, although this may just add a bit more complexity without much benefit.

**Comment by jamslevy** [comment]
One third variation would be where the donor specifies an array of supported function signatures, and the user specifies which of the supported options to use.

**Comment by jamslevy** [comment]
https://github.com/taptrust/trustfund-vouchers/pull/12

**Comment by taptrust** [comment]
@figs999 please review #12 when you have a chance and merge if it is ready or modify if necessary.

**Comment by jamslevy** [comment]
Completed
